rembo10/headphones

- API.md
- headphones/api.py
Added an API command to launch an Active Artist Update.  Personally, I would like to do this once a week on at a set time via cron as opposed to it being based on the time delta from when Headphones was started.
> Active Artist Update can be launched via API

- data/interfaces/default/config.html
- headphones/music_encoder.py
- headphones/webserve.py
The settings in the 'Advanced Encoding Options' section still use the extension of the format selected in the 'Audio Properties' section. For instance when you give the custom argument '-y -acodec flac' while the mp3 format is selected in the 'Audio Properties' section the resulting files will still have the .mp3 extension.
The variable headphones.CONFIG.ENCODEROUTPUTFORMAT is set by the format selected in  'Audio Properties'. With these changes a provided extension in the 'Advanced Encoding Options' section takes precedence.
> Added the option to provide an extension when using 'Advanced Encoding'

- headphones/postprocessor.py
Hello,
When doing the post-processing, in case headphones cannot write in the downloads folder, the sub-folder with "headphones-modified" cannot be created. Instead of using a subfolder, prefer a temporary folder as provided by the tempfile utility. That way, even if the folder is read-only, we can do post-processing.
> postprocessor: use a temporary folder

- .gitignore
- headphones/helpers.py
- headphones/pathrender.py
Hi, I'd like to propose a change to the way Headphones path pattern substitution works. This is a module which implements something more similar to the way foobar2000 allows for formatting: optional blocks and escaped literal text (including $ character). More information in the module docstring.
> Pathrender: a proposal for extended path substitution

- headphones/postprocessor.py
Fix for the bug leaving spurious temp dirs after each album processing, due to
headphones trying to rmtree the subdirectory instead of the temp dir itself.
> postprocessor.py: Delete the proper temp dir after postprocessing

- headphones/webserve.py
This patch prevents exceptions from os.path.isdir() called with unicode folder names.
> webserve.py: Fix scanning artists with non-ASCII letters in dir name.

- headphones/helpers.py
@rembo10 : I just noticed that the pathrender commit was not synced with the most recent change in helpers.py which was now failing, this is a quick fix for that, sorry for the trouble.
> helpers.py: Fix replace_all() broken by commit not in sync

- .travis.yml
Headphones does not require a full virtual machine, it can run using 
Travis-CI's container infrastructure which has higher limits and is 
faster
See https://docs.travis-ci.com/user/workers/container-based-infrastructure/ for more info
> Make travis builds faster

- headphones/transmission.py
If session id from previous request to Transmission is present, try using it and
retry the request with new session id only if the first try fails with status
code 409. This will decrease number of required requests by half.
> transmission.py: Don't request session id in subsequent requests.

- data/interfaces/default/config.html
This is follow up to the change introducing "pathrender.py" and extended path
formatting syntax.
> config.html: Add explanation text for optional elements and single-quote escapes

- headphones/deluge.py
This fixes the pep8 warning that causes the build to fail on develop: 
https://travis-ci.org/rembo10/headphones/jobs/111639439#L289
> pep: fix commenting

- data/interfaces/default/config.html
- headphones/__init__.py
- headphones/config.py
- headphones/deluge.py
- headphones/postprocessor.py
- headphones/searcher.py
- headphones/webserve.py
- Fix #2546 - Always authenticate to avoid expired cookies
- Fix #2540 - Better DL - fix for specific sites, also use HTTPS (without verification for self-signed certificates unfortunately)
- Log scrubbing for some sensitive info
> Deluge Improvements and Fixes

- headphones/__init__.py
- headphones/postprocessor.py
In response to issue report by @emptied in the thread: https://github.com/rembo10/headphones/issues/2466
> postprocessor.py: Safeguard against lack of ReleaseDate in metadata

- headphones/metadata.py
- headphones/metadata_test.py
- headphones/postprocessor.py
This commit adds the possiblity to use variables from tags already present in
the downloaded media files in file, folder and album art renaming routines. The
variable names translate directly to MediaFile field names, so it is now
possible to use variables like $mb_albumid, $genre, $bitrate, $samplerate, etc.
The full list can be read from MediaFile.readable_fields().
> metadata.py: Use arbitrary variables from existing tags or database in renamer

- headphones/helpers.py
- headphones/helpers_test.py
- headphones/importer.py
- headphones/librarysync.py
- headphones/mb.py
- headphones/postprocessor.py
- headphones/webserve.py
Track matching is performed using 'CleanName' which up to now was obtained in
convoluted way, which effectively removed any non-ascii alphanumeric characters
but at the same time left some trash preventing the names to be matched due to
whitespace differences. Current implementation allows for differentiation based
on unicode characters (which are normalized beforehand), but at the same time
allows only alphanumeric chars to be taken into account and coalesces remaining
spaces. Based on observations on several-tens GiB library, this allows for much
better ratio of automatic track matches.
> helpers: Replace cleanName() implementation to get much higher match ratio.

- .pep8
- headphones/postprocessor.py
- headphones/searcher.py
Fix `E261 at least two spaces before inline comment` in the code.
> pep: fix e261

- headphones/__init__.py
FIX: bug with fullname of `headphones.exceptions`, visible just for pyflakes
> Fix broken build (headphones.exceptions for softchroot)

- headphones/postprocessor.py
Fix the infinite addition of .orig. into the file suffix where filenames would tentatively become FILENAME.orig.orig.orig.orig.orig.orig.orig.orig.nfo etc, before causing an exception in processing.
> Fix infinite .orig.nfo extension suffix addition

- README.md
Their lack of alignment irked me a bit :sweat_smile: 
Old:
New:
What do you think?
> Custom build badges in readme

- init-scripts/init.freebsd
Several things were done wrong or badly. See [Practical rc.d scripting in BSD](https://www.freebsd.org/doc/en/articles/rc-scripting/article.html), [`rc`](https://www.freebsd.org/cgi/man.cgi?query=rc&sektion=8&manpath=freebsd-release-ports), [`rcorder`](https://www.freebsd.org/cgi/man.cgi?query=rcorder&sektion=8&manpath=freebsd-release-ports) and [`rc.subr`](https://www.freebsd.org/cgi/man.cgi?query=rc.subr&apropos=0&sektion=8&manpath=FreeBSD+10.3-RELEASE+and+Ports&arch=default&format=html).
- `/usr/sbin/daemon` is not really necessary. `command` and `command_interpreter` work perfectly fine
- `command_args` was used incorrectly. I replaced it with `headphones_flags`.
- I don't like to `REQUIRE` sabnzbd as other downloaders are compatible. It does meet the guidelines as it does work …
> Fixed FreeBSD init script.

- headphones/rutracker.py
rutracker.org randomly makes a redirection upon login (HTTP 302). That was fooling the current system that couldn't find the cookie in request's response  - in my case, 80% of the time. This is probably the cause for issue #2595.
```
In [5]: r = requests.post(loginpage, data=post_params)
In [6]: r.cookies.keys()
Out[6]: []
```
However by just checking for cookie's presence in request history we're able to fix the existing login :
```
In [17]: r.history
Out[17]: (<Response [302]>,)
In [18]: r.history[0].cookies.keys()
Out[18]: ['bb_data']
```
> Fix Rutracker loggin by looking for the cookie in request history

- headphones/searcher.py
Although the API from the old domain is still working, I am anticipating its future shutdown. 
The API on the new domain is now functionnal.
> Update T411 new domain ( t411.li )

- data/interfaces/default/config.html
- headphones/config.py
- headphones/rutracker.py
- headphones/webserve.py
Trouble logging in may be caused due to captcha. Using a pre-existing cookie from an authenticated browser session may serve as a workaround.
> rutracker optional session cookie

- headphones/webserve.py
Without this SQLite will order the results by whichever column happens to be the fastest for it. This will usually result in the rows being sorted by the primary key (or rowid).
Sorting by release date also matches the sort order of the "upcoming" albums list.
> Sorted wanted albums by release date.

- headphones/deluge.py
Check _if_ Deluge WebUI daemons exist before checking _how many_ exist, fix #3010
> Deluge WebUI daemons - fix #3010

- Headphones.py
This fixes broken special characters(like umlauts, showing as ") in the console output. 
Unfortunately does not fix headphones running on Windows not seeing folders with japanese characters etc but at least gets rid of a small annoyance.
locale.getpreferredencoding() on Windows returns 'cp1252' (at least on a 1252 locale), but this encoding isn't actually used for filenames. sys.getdefaultencoding() in my testing returns 'ascii' on Python 2.7(and 'utf-8' on 3.6) so it gets set to UTF-8 in the end.
> Fix SYS_ENCODING selection on Windows

- headphones/searcher.py
When this occurs, the following exception is raised
```
30-Mar-2018 16:21:53 - ERROR :: Thread-17 : An unknown error occurred trying to parse the feed: 'NoneType' object has no attribute 'string'
Traceback (most recent call last):
File "/opt/headphones/headphones/searcher.py", line 1357, in searchTorrent
size = int(item.size.string)
AttributeError: 'NoneType' object has no attribute 'string'
```
Replaces #3103
> Items from torznab are not returned when size is defined as torznab:attr

- headphones/searcher.py
Previous behavior was to arbitrarily pick torrent by size. This commit will instead pick the torrent with the highest amount of seeders. This filtering is preferred as the torrent with the highest amount of seeders is generally the best result - community consensus of which upload is best by popularity, provides the fastest download speed, and gives you the most upload potential. 
Testing results:
id 1159880 = 194 seeders
id 1163752 = 9 seeders
id 1162109 = 6 seeders
```
03-Jul-2018 09:43:04 - INFO    :: CP Server Thread-6 : Marking album: a63e5fa6-d6ad-47bd-986d-4a27b0c9de70 as wanted...
03-Jul-2018 09:43:04 - INFO    :: CP Server Thread-6 : Searching for wanted albums
03-Jul-2018 09:43:04 - INFO    :: CP Server Thread-6 : Searching for "Nine Inch Nails - Bad Witch" since it was marked …
```
> sort Apollo.rip results by number of seeders

- headphones/helpers.py
I wasn't able to test this as much as I wanted due to my CIFS mount issue being resolved.  However, this workaround should be helpful for any issues where only the shutil.copystat() fails.  See issue #2674 for more details.
> Workaround for issue #2674

- headphones/deluge.py
- lib/apscheduler/job.py
- lib/apscheduler/schedulers/base.py
- lib/mutagen/apev2.py
- lib/pygazelle/api.py
- lib/pygazelle/artist.py
Hi, I've been testing the latest develop branches with Python 3.10 (not sure which version is the target)
For now, I had to make the following changes to make things work with my config:
- deluge: b64encode returns bytes, transform into string before
serializing to JSON.
- deluge: no more need to try different encodings for the torrent
filename or the base64-encoded content, should all be unicode strings
with Python 3
- collections.abc: Iterable, Mapping, MutableMapping moved from
collections to collections.abc since Python 3.3
- pygazelle: html.parser.HTMLParser().unescape() moved to
html.unescape() in Python 3.4
> Fixes for Python 3.10

- headphones/rutracker.py
CloudFlare seems to block request without User-Agent header. This fix should be enough to bypass that.
> Fix for 503 error from CloudFlare.

- data/interfaces/default/config.html
- headphones/config.py
- headphones/deluge.py
- headphones/searcher.py
- headphones/webserve.py
- Adds a "download directory" option to Deluge - this is the path where torrent data will be downloaded to. Configurable in the UI. Use in conjunction with the exsiting "move when completed" option to move the data to a new location afterwards. 
- Updated deluge.py `_add_torrent_file` function to set "pause", "deluge move when completed", and new "download directory" options during the torrent creation call, rather than making multiple calls afterwards. 
- Removes Deluge "beta" designation in UI
> Deluge udpate

- data/interfaces/default/config.html
- headphones/config.py
- headphones/searcher.py
- headphones/webserve.py
- lib/pygazelle/api.py
Several improvements:
- update redacted url
- add (optional) apikey sign-in to redacted instead of username/password (allows to enable 2FA sign-in)
- merge code for Orpheus & Redacted (same code, except for album_type filtering, which was only implemented in Orpheus code and is now available also for Redacted)
- simplify sorting code (only 2 options instead of multiple redundant sorts)
> Gazelle improvements

- headphones/deluge.py
Fix torrent file encoding for deluge
- received content is bytes
- we need to convert this content into base64
- we then need to convert base64 bytes into base64 string to include in the json data binary
Fixes #3362
> Fix deluge torrent upload
