- headphones/api.py
Added API call so you can get a list of what is currently being downloaded.
> Added API call getSnatched

- headphones/postprocessor.py
Fixed for spelling "writable" in postprocessor.py from "writeable"
> Fixed for spelling "writable" in postprocessor.py

- data/interfaces/default/config.html
- headphones/config.py
- headphones/searcher.py
- headphones/webserve.py
https://github.com/rembo10/headphones/issues/2329
This pull effectively gives Headphones an additional ~30 torrent search providers. 
Tested and working when applied to the master branch. On dev branch I'm unable get album info for artists so I can't test.
> Implemented Jackett (Custom Torznab) option for Torrent Search Providers

- headphones/librarysync.py
Bug prevented progress from being properly displayed on albums with a track count not divisible by 10
> Fixed a bug in track matching where only progress exactly divisible by 10 was displayed

- headphones/unittestcompat.py
Sorry... Here is patches.
I checked: on Travis all works..
> Fix for broken unittestcompat

- headphones/cache.py
Implement Webmoshers ( https://github.com/webmosher ) fix for issue #2485 per https://github.com/rembo10/headphones/issues/2485#issuecomment-180047097
> Resolve image caused uncaught exception.

- headphones/postprocessor.py
Also lowercase variant $date, both resolve to the same field ReleaseDate taken
from metadata.
> postprocessor.py: Allow $Date variable in file/folder name patterns.

- .pep8
- headphones/__init__.py
- headphones/albumart_test.py
- headphones/config.py
- headphones/config_test.py
- headphones/deluge.py
- headphones/exceptions.py
- headphones/pathrender.py
- headphones/softchroot.py
- headphones/softchroot_test.py
- headphones/transmission.py
- headphones/unittestcompat.py
- headphones/webserve.py
Fix pep error on `E302 expected 2 blank lines, found 1`
> pep: fix E302

- .pep8
- headphones/postprocessor.py
Fix pep `indentation is not a multiple of four`
> pep: fix E111

- .pep8
- headphones/searcher.py
Fix `E262 inline comment should start with '# '` in code.
> pep: fix e262

- data/interfaces/default/config.html
Fix a small typo with "Musicbrainz".
2nd PR as I messed up the first.
> Fix typo with Musicbrainz

- headphones/helpers.py
- headphones/metadata.py
- headphones/metadata_test.py
fix for some obscure/hard to spot cases when some fields may have None values
> metadata: Additional protection against NPEs

- headphones/__init__.py
- lib/unittestcompat.py
> FIX: unittestcompat now support tests without python-doc.

- headphones/__init__.py
V2 aiff lossless file inclusion to develop
> aiff and aif lossless file addition v2

- .pep8
- headphones/albumart_test.py
- headphones/config_test.py
- headphones/deluge.py
- headphones/librarysync.py
- headphones/request.py
- headphones/softchroot.py
- headphones/softchroot_test.py
- headphones/webserve.py
Fix `E265 block comment should start with '# '` in the code.
> pep: fix e265

- .pep8
- headphones/albumswitcher.py
- headphones/cache.py
- headphones/importer.py
- headphones/librarysync.py
- headphones/mb.py
- headphones/music_encoder.py
- headphones/nzbget.py
- headphones/postprocessor.py
- headphones/searcher.py
- headphones/webserve.py
- headphones/webstart.py
Fix the following PEP8 errors in the code:
- `E124 closing bracket does not match visual indentation`
- `E125 continuation line with same indent as next logical line`
> pepx: fix e124 and e125

- .pep8
- headphones/importer.py
- headphones/librarysync.py
- headphones/mb.py
- headphones/notifiers.py
- headphones/nzbget.py
- headphones/pathrender_test.py
- headphones/postprocessor.py
- headphones/rutracker.py
- headphones/searcher.py
- headphones/versioncheck.py
- headphones/webserve.py
Fix the following PEP8 errors in the code:
- `E121 continuation line under-indented for hanging indent`
- `E122 continuation line missing indentation or outdented`
> pep: fix e121 and e122

- lib/unittestcompat.py
added new method for compatibility with python 2.6 (unittests)
> Unitestcompat: assertItemsEqual added

- data/interfaces/default/base.html
- headphones/versioncheck.py
I have added another one link to the footer of interface. Just for peoples, who use the **forks** of this repo
> UI: Added link to the fork to the footer of Web UI

- data/interfaces/default/config.html
- headphones/deluge.py
- headphones/searcher.py
> Waffles move from .fm to .ch

- headphones/searcher.py
Changed the url used for searching waffles from https://www.waffles.ch/browse.php to https://waffles.ch/browse.php.
> Update to searcher.py to work with waffles.ch

- Headphones.py
- init-scripts/init.ubuntu
Also, added option `HP_HOST` to ubuntu init scriptm for option --host.
> [+] --host command line option

- headphones/crier.py
- headphones/webserve.py
- lib/cherrypy/wsgiserver/wsgiserver2.py
For debugging when weird stuff is going on, this handler is an easy knob to hit with wihch to trigger a thread state dump to logs.  Useful if you're trying to understand what Headphones is up to.
> Add thread dumper to allow for easier debugging.

- headphones/deluge.py
Removed Deluge password logging in case of empty password. It was avoiding Deluge to work
> Handling Deluge empty password

- headphones/searcher.py
Release date as returned by Musicbrainz usually contains the full date (Year-Month-Day)
but it may as well be just Year-Month or even just the year.
For instance I had this set of data :
Which was giving errors like this one :
> WARNING :: Thread-12 : No valid date for: xxxxx. Skipping automatic search
We now try different date format patterns before raising an error, from the most accurate (Year-Month-Day) to the less accurate (just the year).
> Accept partial release date for search

- data/interfaces/default/config.html
> Use HTML escaping for password fields

- headphones/searcher.py
Fixed a bug where T411 was not checked when choosing specific download
> T411 specific download bugfix

- headphones/deluge.py
Added HTTP headers related to JSON content-type. Fixes issues (#2865) related to Deluge 1.3.14 update.
> Added JSON-related HTTP headers

- data/interfaces/default/config.html
- headphones/deluge.py
- Deluge: check if torrent finished seeding before deleting
- Fix typo causing Qbittorrent config to show while Deluge is selected
> Fix Qbittorrent config appearing while Deluge is selected + Deluge check if torrent seeding before removal

- headphones/deluge.py
> More exception handling for Deluge torrent removal

- README.md
It's just a space, but the title was bugging me. :)
> Fix title markdown

- headphones/webserve.py
Fixed bug (#2933 at least) where an artist will null name errors when trying to remove from library as logger is trying to concat artist name (NoneType) with string
> Bug (#2933) - Can't remove artist with name "null"

- headphones/__init__.py
Fixes #2987
Looks like this issue was introduced in bc0ce99adfa7df8176d874581d6c83a19fcc251e.
> Fix TypeError in dbcheck()

- headphones/searcher.py
Fixes an old issue https://github.com/rembo10/headphones/issues/2132 - now applies to apollo.rip
> Make apollo.rip searches specific to the album type

- data/interfaces/default/config.html
- headphones/config.py
- headphones/notifiers.py
- headphones/postprocessor.py
- headphones/searcher.py
- headphones/webserve.py
Initial Join by Joaoapps API Notification Support.  See issue #2712
> Join notification support

- headphones/deluge.py
Hopefully fixes #3014 - thanks to @tillmanj
> Added UTF-8 header for encoding issues

- headphones/deluge.py
> Deluge encoding issues with unicode torrent names

- lib/cgi/__init__.py
- lib/imghdr/__init__.py
The packages `imghdr` and `cgi` were removed from Python 3.13, so this PR re-adds them. See issue #3365.
I've tested in Python 3.13 on Debian 13.
> Add imghdr and cgi
